import type { Metadata } from "next"
import { Poppins } from "next/font/google"

import { Toaster } from "@/shared/components/ui/Toaster/Toaster"

import "./globals.css"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Trackx",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main>{children}</main>
        <div className="relative z-[1000]">
          <Toaster />
        </div>
      </body>
    </html>
  )
}
